#!/bin/bash

out=chi2.dat 
p=param

Rmin=10
Rmax=50
dmin=1
dmax=30 

rm $out

#for (( R = $Rmin ; R <= $Rmax; R++))
#do 
#for (( d = $dmin ; d <= $dmax; d++))
#do 

for  R in $(seq $Rmin 1 $Rmax)
do
for  d in $(seq $dmin 1 $dmax)
do
 
#Make param
#	echo $R $d
	echo " " > $p
	echo " " >> $p
	echo "-150 150 1" >> $p
	echo "Vo" >> $p
	echo $R >> $p
	echo "d" >> $p
	echo $d >> $p
#Run model
	./ehalf | tail -1 >> $out
done
done

	
